# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    alacritty.toml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pibouill <pibouill@student.42prague.com>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/07 14:31:26 by pibouill          #+#    #+#              #
#    Updated: 2025/01/07 14:39:03 by pibouill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]

[font]
size = 14

[font.normal]
# family = "JetBrainsMono"
# style = "Medium"
family = "Ubuntu Mono Nerd Font"
style = "Regular"

[window]
opacity = 0.9
decorations = "none"

[window.padding]
x = 7
y = 0

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"
